### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by thomasbnt** [endel/shieldsio-patreon#1]
Hello ! Thank you for your project, but it has recently broken :disappointed: 

Example : 
[![Patreon](https://img.shields.io/endpoint.svg?url=https://shieldsio-patreon.herokuapp.com/thomasbnt&style=flat-square)](https://www.patreon.com/thomasbnt)

**Comment by endel** [comment]
Hey @thomasbnt, my monthly Heroku usage has been exceeded today. You can deploy your own version of this in your Heroku account to fix this. Tomorrow this should be back again, though, since Heroku usage re-sets every month. Cheers.

**Comment by thomasbnt** [comment]
Ow okay! thanks for answer me!
