### ISSUE TITLE
static badge should be returned whenever the dynamic badge is inaccessible

### ISSUE THREAD

**Issue by sporeball** [endel/shieldsio-patreon#11]
badges created with this endpoint still return "custom badge -- inaccessible" a **lot** of the time:

![image](https://user-images.githubusercontent.com/12767408/98592158-28c6a080-2286-11eb-862c-8861beda9911.png)

i use this endpoint in the READMEs for most of my repos (one of which is on npm), as well as my profile README, so this is less than ideal.

i'm assuming this problem is due to lack of availability on Shields' part, rather than Vercel's. to get around this, it would be fantastic if the Vercel endpoint automatically returned a static badge (e.g. https://img.shields.io/static/v1?label=&message=patreon&logo=patreon&color=555&style=for-the-badge) whenever the custom one cannot be accessed, as i've never seen the static badges go down:

![image](https://img.shields.io/static/v1?label=&message=patreon&logo=patreon&color=555&style=for-the-badge)

**Comment by endel** [comment]
Hi @sporeball, thanks for reporting! I think Patreon has been changing this recently, I've updated the endpoint to retrieve the data differently this time, it shouldn't crash anymore! Let me know if that works for you now. Cheers!
