### ISSUE TITLE
badge broken: 'Custom Badge | Inaccessible' 

### ISSUE THREAD

**Issue by problame** [endel/shieldsio-patreon#3]
Just noticed that the badge is broken again:

![image](https://user-images.githubusercontent.com/956573/67978898-688e8d00-fc1b-11e9-8732-5885c6e33a94.png)

**Comment by endel** [comment]
Hi @problame, this badge is hosted on Heroku Free Plan, and my free hours for this month have expired. I'd suggest hosting your own version of it on your account. Cheers

**Comment by moshfeu** [comment]
And again :(

**Comment by moshfeu** [comment]
I created a server based on your code

<img src="https://img.shields.io/endpoint.svg?url=https://moshef9.wixsite.com/patreon-badge/_functions/badge/?username=codingcoach_io" />

    https://moshef9.wixsite.com/patreon-badge/_functions/badge/?username={username}

**Comment by endel** [comment]
Thanks @moshfeu, my Heroku free plan is usually being exhausted in the last days of the month.

**Comment by moshfeu** [comment]
Understandable :)
Thanks for the inspiration.

**Comment by endel** [comment]
I've added an **ATTENTION** section in the readme with instructions how to deploy your own version of this on Heroku https://github.com/endel/shieldsio-patreon#attention
