### ISSUE TITLE
How do I add a link to my patreon page in the markup?

### ISSUE THREAD

**Issue by beriniwlew** [endel/shieldsio-patreon#6]
Newbie question here, but thought you might be able to help answer this question.

**Comment by endel** [comment]
Hi @beriniwlew, most Markdown parsers allow simple HTML tags, here's how it is on my README's. Just change "endel" to your username

```
<a href="https://patreon.com/endel"><img src="https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fshieldsio-patreon.herokuapp.com%2Fendel&style=for-the-badge" /> </a>
```

I highly suggest you to deploy your own version of this on Heroku or somewhere else, though, because of https://github.com/endel/shieldsio-patreon/issues/3

**Comment by beriniwlew** [comment]
Thank you!  I appreciate it.   Wasn't 100% that markup language supported HTML.
